### ISSUE TITLE
Add a `cli_glue` type function to the package?

### ISSUE THREAD

**Issue by rundel** [r-lib/cli#222]
I've now had several packages where it is necessary to construct a text string using cli formatting in a different scope from where the message will eventually be printed for the user. I find it very helpful to be able to use the inline text formatting in these cases but I don't have an obvious way of restructuring the code so that this can be contained within a `cli_text` or similar call. 

For these packages I've added a simple function along the lines of 
```r
cli_glue = function(..., .envir = parent.frame()) {
  txt = cli::cli_format_method(cli::cli_text(..., .envir = .envir))
  # cli_format_method does wrapping which we dont want at this stage so glue things back together.
  paste(txt, collapse = " ")
}
```
This seems like a common enough use case that it potentially belongs in the package?  It also seems like it might be useful in the context of #142 and seems inline with the addition of the `pluralize` function.

**Comment by gaborcsardi** [comment]
Can you show an example (link to code is enough) where this is useful? Thanks!

**Comment by rundel** [comment]
This is used a fair bit in `ghclass`, particularly with the status / error messaging - you can take a look at https://github.com/rundel/ghclass/blob/6ed836c0e3750b4bfd1386c21b28b91fd7e24b4a/R/util_safely.R#L146-L183 for an idea of where I am using that function to generate a more complex output.

**Comment by gaborcsardi** [comment]
I kind of dismissed this issue in my head, without thinking too much about it, by hoping that people can just use plain `glue()` or `glue_data()` in this case. But can you actually just use `glue()`?

**Comment by rundel** [comment]
For the `error_msg_tree` function there yes I think regular glue would be fine - in the higher level functions that call status_msg are using thinks like `{.val {x}}` or `{.field {x}}` which is why I had opted for the `cli_glue`. See https://github.com/rundel/ghclass/blob/6ed836c0e3750b4bfd1386c21b28b91fd7e24b4a/R/issue_create.R for an example.

**Comment by rundel** [comment]
The inline text formatting and pluralization functionality are the primary drivers here.

**Comment by gaborcsardi** [comment]
Yeah, that makes sense. Let me think about this a bit. Maybe it is possible to avoid adding an `.envir` argument to all cli functions....

**Comment by rundel** [comment]
One other thing to quickly note - the `cli_glue` function above uses `cli_text` which seems to strip newlines and trim whitespace for all inputs which is something which would ideally be controllable. 

```r
cli_glue("   a\nb\nc")
# [1] "a b c"
```

**Comment by jennybc** [comment]
I have developed this exact need myself.

**Comment by gaborcsardi** [comment]
Yes, of course this boils down to the usual issue: you cannot pass code around without its evaluation environment.

OTOH, many (all?) cli function are already taking an `.envir` argument, that you can use:

```r
my_cli_text <- function(...) {
  cli_text(..., .envir = parent.frame())
}

x <- "notthis"
f <- function(x = c("yes", "yep", "yaah")) {
  my_cli_text("th{?is/ese} {?is/are} {?it/they}: {.path {x}}")
}
f()
```

Does this solve your problems? Is there any cli function that does not support this?

**Comment by jennybc** [comment]
A key component of what I'm thinking of is that I don't want to emit the text right away. I want cli to format it and I'll take care of emitting it later. Hopefully I'm not muddying the conversation.

https://github.com/r-lib/gargle/blob/73ec7aa8ca8c1094e7efb5494b4d058f582541af/R/ui.R#L112-L122

Basically it feels like cli is designed to "format and emit" and to just format you have to wrap things in `cli::cli_format_method()` to achieve "format only".

Again, I hope I'm thinking of the same thing here as @rundel.

If so, I don't think `cli_glue()` is a good name, because I think of the cli functions as already doing what glue does (interpolation). (Although it's true that glue does *not* emit via `message()` or `inform()`, so maybe that's what @rundel is thinking of.)

It feels like `cli_format()` is the right name -- I even called my first version this, but then I realized I was masking the existing [`cli::cli_format()`](https://cli.r-lib.org/reference/cli_format.html) and changed my name to `cli_this()`.

**Comment by rundel** [comment]
This sounds the same as my use case - due to a call hierarchy I don't necessarily have access to the needed variables when emitting so I want to setup the formatting and then print later. 

The `cli_glue` was because I was very much using this like glue to create a string that I was then printing later which is definitely less than ideal.

**Comment by gaborcsardi** [comment]
> A key component of what I'm thinking of is that I don't want to emit the text right away. I want cli to format it and I'll take care of emitting it later. Hopefully I'm not muddying the conversation.

One potential issue with that is the environment is potentially different when you format and when you emit the text. E.g. you format it and store it in an object, but then when you emit it there is a `sink()` which should not use ANSI color. Or, on Windows a `sink()` will have no Unicode support.

So I think in general it is safer to store the information you need to format the text, and only format & emit it when you need to.

OTOH I don't mind have a function for this, if you think you still want to do it. `cli_format()` would be a good name indeed, it is a pity that it is taken. Maybe `cli_record()` would make sense? I am planning to implement it by recording the message(s) anyway.

**Comment by jennybc** [comment]
> This sounds the same as my use case - due to a call hierarchy I don't necessarily have access to the needed variables when emitting so I want to setup the formatting and then print later.

So my use case **is** different from @rundel's. I don't have this particular challenge of truly needing to delay evaluation/interpolation.

I just want to format something and then hold on to it for a moment and emit a bit later, e.g., combined with other stuff.

**Comment by gaborcsardi** [comment]
I decided not to do this now. It is a very thin wrapper on `cli_format_method()`, which does not have a nice name, but otherwise it does what you need.

It also feels like that having more parameters in `cli_glue()` basically introduces an alternative text formatting code path, which does not seem like a good idea.

Pre-formatting messages and emitting them later is also somewhat fragile: https://github.com/r-lib/cli/issues/222#issuecomment-810058105
