### ISSUE TITLE
Rename `cli_memo()` to `cli_bullets()`?

### ISSUE THREAD

**Issue by lionel-** [r-lib/cli#250]
For consistency with `format_bullets()`. Also "memo" is a little abstract compared to "bullets".

**Comment by gaborcsardi** [comment]
It is intended to be a little abstract, do highlight the difference from `cli_ul()` etc. So I would keep the `cli_memo()` name. FWIW this has been released already, so strictly speaking it is a breaking change.

**Comment by lionel-** [comment]
It makes sense to differentiate from cli-ul etc. However `cli_memo()` isn't very descriptive about what it's doing. Since cli and rlang are now part of the core set of r-lib packages, I think we should coordinate and strive to make them consistent.

Regarding the breaking change, probably a quick deprecation cycle should work since it's very new. On the other hand we're renaming `rlang::format_error_bullets()` to `rlang::format_bullets()` in the next release, so it is still time to change the name to `rlang::format_memo()`. However I think "bullets" is more descriptive and it also connects to the principle of error messages as bullets of our style guide.

**Comment by gaborcsardi** [comment]
Well, `cli_memo()` is more abstract than `rlang::format_bullets()`. It doesn't even need to output bullets, actually, even though that is the default. But you can also format it differently if you want:

```
❯ cli_div(theme = list(".memo-item" = list(fmt = function(x) boxx(ansi_align(ansi_strwrap(x, 40), width = 40)))))
❯ cli_memo(c(lorem_ipsum(1,1), x = lorem_ipsum(1,1), "i" = lorem_ipsum(1,2)))
┌──────────────────────────────────────────────┐
│                                              │
│   Quis nostrud magna velit cillum ea qui     │
│   est.                                       │
│                                              │
└──────────────────────────────────────────────┘
┌──────────────────────────────────────────────┐
│                                              │
│   ✖ Cillum aliqua aliquip ad nisi.           │
│                                              │
└──────────────────────────────────────────────┘
┌──────────────────────────────────────────────┐
│                                              │
│   ℹ Et tempor sint dolor anim esse sunt      │
│   tempor sit deserunt commodo.               │
│                                              │
└──────────────────────────────────────────────┘
```

The semantic cli functions tend to be more abstract, which is kind of the point. They abstract away the exact details of the output. That's why `cli_alert_success()` is a better name than `cli_tick()` or `cli_h1()` is a better name than `cli_text_rule()`.

Also, you don't actually need to call `cli_memo()` to create error messages, there is `cli_abort()` now, which calls it for you.

This said, I don't mind that much, usually it will be a bullet list or something similar, so I can rename it to `cli_bullets()`.

**Comment by lionel-** [comment]
Thanks!

> Also, you don't actually need to call cli_memo() to create error messages, there is cli_abort() now, which calls it for you.

This is symmetric to how `abort()` calls `format_bullets()`.
