### ISSUE TITLE
Improve the wrapping in rstudio if there is no error inspector

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/cli#288]
Maybe we can use `getOption("error")` to detect this:
```r
> getOption("error")
(function () 
{
    .rs.recordTraceback(TRUE, 5, .rs.enqueueError)
})()
> getOption("error")
(function () 
{
    .rs.breakOnError(TRUE)
})()
```

**Comment by hadley** [comment]
I don't see the error inspector when I'm using `rlang::abort()`:

```R
f <- function(f) g(f)
g <- function(f) h(f)
h <- function(f) i(f)
i <- function(f) f("This is an error")

f(stop)
f(rlang::abort)
```
<img width="948" alt="Screen Shot 2022-03-05 at 11 56 47" src="https://user-images.githubusercontent.com/4196/156894801-4b03aa17-f494-49a6-a280-76fd78872a92.png">


Even if you do see it, I think we'd now only need to wrap the first line of the error, since we're now putting `Error:` on its own line (and the RStudio buttons only take up 2 lines)

**Comment by hadley** [comment]
Same behaviour with default value for `options(rlang_backtrace_on_error)`

![Uploading Screen Shot 2022-03-05 at 11.59.09.png…]()

**Comment by gaborcsardi** [comment]
> I don't see the error inspector when I'm using rlang::abort():

I am not sure why that is the case, but then I can turn off the special casing.
