### ISSUE TITLE
How to update multiple progress bars using IDs?

### ISSUE THREAD

**Issue by hongyuanjia** [r-lib/cli#371]
I would like to write a job manager using {cli} progress bars. The goal is to have one main progress bar with `type = "tasks"`, and several child progress bars showing the status of each job. Previously I use one `progress::progress_bar` as the main progress and print the status of each job at different times using progress messages. The problem with this approach is that the message is sticky and not dynamic. How could I do this using {cli}'s progress bars? I tested the code below to create multiple progress bars and update each of them, but nothing showed up. Btw, thanks for the **awesome** {cli} and {progress} packages!

```r
f <- function() {
    pbs <- character(5)
    for (i in seq.int(5)) {
        pbs[i] <- cli::cli_progress_bar(
            total = 1, type = "custom",
            format = "{.alert-start Job {i}}",
            current = FALSE, clear = FALSE
        )
    }
    for (i in 1:5) {
        Sys.sleep(1)
        cli_progress_update(id = pbs[[i]])
    }
}
f()
```

**Comment by gaborcsardi** [comment]
If you have multiple things running in parallel, then the best is to create a single progress bar that is a summary of all jobs.

Otherwise if the progress bars are switching back and forth, it'll not look good. You'll get this kind of output: https://github.com/r-lib/pak/issues/330#issue-1045054536
