### ISSUE TITLE
Deprecate/superseded `cli_alert_*()`

### ISSUE THREAD

**Issue by hadley** [r-lib/cli#468]
In favour of named vector input to `cli_inform()`

**Comment by gaborcsardi** [comment]
`cli_inform()` is not great, actually, because it does not work well with cli progress bars and status bars. The issue is that rlang is in charge of outputting the output, and it does not know about the cli status bar, and it will just overwrite it. So `cli_bullets()` is actually better, that keeps the status bar intact.

I think it is fine to support `cli_alert_*()` as well, it does not seem to me that we gain much from deprecating it. They are all thin wrappers on top of the same machinery. We can still prefer `cli_bullets()` or `cli_inform()` in our packages of course, without a formal deprecation.

**Comment by hadley** [comment]
Ah that makes sense

**Comment by gaborcsardi** [comment]
No, cli is always outputting to stdout at the rstudio console or in a terminal.

**Comment by hadley** [comment]
Oh so #465 should fix the orange text here:

<img width="628" alt="Screen Shot 2022-05-24 at 13 54 26" src="https://user-images.githubusercontent.com/4196/170111219-fc9d56d6-c363-406c-ac52-43cf669e481c.png">
