### ISSUE TITLE
cli hyperlinks with base functions.

### ISSUE THREAD

**Issue by olivroy** [r-lib/cli#598]
Hi,

I was wondering if it would be possible to allow base functions to have hyperlinks.

It would be handy if 
```r
cli::cli_text("{.run names(.Last.value)}")
```

worked.

The workaround I found is to create my own package and to wrap `base::names()` function in it, so I can do this.

```r
cli::cli_text("{.run mypkg::get_names()}")
```

with 
```r
get_names <- function(x = .Last.value) { 
  names(x)
}
```

Thanks for the great package!

Actually I use this as I override the tibble printing method. When a data frame is long, I like to have a clickable hyperlink to display the names of the last value.

**Comment by moodymudskipper** [comment]
Here are the rules I got from the linked thread, since I believe those are not documented yet : 

* base, utils, stats: are forbidden
* testthat, devtools, usethis, rlang : hyperlinks always run code, even when not attached
* Other packages : hyperlinks run code if the package is attached (having the namespace loaded is not enough), otherwise just print to the console so user can see the code and validate

The reason as I understand it is that the hyperlink could have dangerous behavior, like removing files or objects, so for instance we forbid base so you can't `rm()`. You might wrap `rm()` in a custom function but then the function would have to be in an attached package so it's somewhat safer, though it seems to me it's quite easy to hack around those measures.

**Comment by gaborcsardi** [comment]
Closing as cli cannot do anything about this.
