### ISSUE TITLE
With `cli::col_bg_white()`, could text be black by default?

### ISSUE THREAD

**Issue by olivroy** [r-lib/cli#693]
In light theme, it looks pretty good.

with theme = Chrome:

```r
cli::bg_white("aaa")
```
![image](https://github.com/r-lib/cli/assets/52606734/74e35959-1e52-4a29-bc91-084ed8ed339f)

On some dark themes, for example, using 

```r
rstudioapi::applyTheme('Cobalt')
```

![image](https://github.com/r-lib/cli/assets/52606734/700a8a9e-6cf8-4f9d-abb7-004366301435)

text is not readable.

Could the default be tweaked a bit ? or otherwise, is there a way I can do I do this myself?

Text seems to appear white by default in most `bg_*()` fn, but on bg_cyan,  bg_green, bg_yellow black text seems to be a better choice for readability.

**Comment by trevorld** [comment]
You can explicitly set both the background color and foreground color using `combine_ansi_styles()` e.g.

```r
library(cli)
black_on_white <- combine_ansi_styles(bg_white, col_black)
black_on_white("aaa")
```

If you're terminal has "truecolor" support then instead of using the system palette "colors" you can even explicitly set the foreground/background colors using `"#RRGGBB"` color strings using `make_ansi_style()` (with `combine_ansi_styles()`).

**Comment by gaborcsardi** [comment]
Yeah, we set bg and fg colors independently, and I think for simplicity we should keep it that way.
